export default [
  "Apa kenangan favoritmu saat berkencan denganku?",
  "Apa memori seksual favorit kamu tentang kami?",
  "Makanan apa yang mengingatkanmu padaku?",
  "Kapan terakhir kali kamu memikirkan aku secara positif?",
  "Apa hal favorit kamu yang aku lakukan untuk kamu?",
  "Film apa yang mengingatkanmu pada kami?",
  "Di antara orang tua kamu, siapa yang paling kamu sukai?",
  "Manakah dari anak-anak kami yang paling seperti kamu? atau jika kamu belum menjadi orang tua: Apakah kamu pernah membayangkan memiliki anak?",
  "Apa fitur fisik terbaik aku?",
  "Apa yang paling kamu sukai yang aku lakukan di tempat tidur?",
  "Apa waktu favorit kamu untuk menjadi intim?",
  "Apakah kamu lebih suka berciuman atau berpelukan?",
  "Kapan kamu tahu kamu ingin menjadi monogami dengan aku?",
  "Apakah kamu pernah cemburu jika kamu melihat aku berbicara dengan orang lain yang menarik?",
  "Apakah kamu pernah bermimpi tentang aku?",
  "Menurut kamu apa yang paling perlu kita perbaiki dalam hubungan kita?",
  "Jika kamu sakit, apakah kamu pikir aku akan ada untuk merawat kamu?",
  "Apakah kamu percaya bahwa aku mencintaimu?",
  "Kapan kamu tahu kamu ingin menciumku?",
  "Apa aktivitas non-seks favorit kamu yang kita lakukan bersama?",
  "Sebagai seorang anak, apakah kamu mempercayai kedua orang tua kamu?",
  "Apa hal favorit kamu yang pernah aku lakukan untuk acara khusus untuk kamu?",
  "Apa fantasi seksual favorit kamu?",
  "Apa posisi seksual favorit kamu?",
  "Apakah kamu pernah berpikir tentang aku secara seksual di siang hari?",
  "Apa yang bisa aku lakukan untuk membuat kamu lebih mempercayai aku?",
  "Kapan kamu merasa paling dilindungi dan diperhatikan?",
  "Apa yang bisa aku lakukan untuk memastikan kamu merasa aman bersama aku?",
  "Ketika kita hang out dengan teman-teman, apakah aku membuat kamu merasa bahwa kamu masih menjadi prioritas aku?",
  "Saat kita bersama keluargaku, apakah aku membuat kamu merasa seperti kamu masih menjadi prioritas aku?",
  "Apakah kamu memiliki pelanggar kesepakatan, hal-hal yang akan membuat kamu serius mempertimbangkan kembali hubungan kita?",
  "Apa hal pertama yang kamu pikirkan tentang aku?",
  "Kapan kamu pertama kali berpikir aku menarik?",
  "Menurut kamu berapa lama orang harus menunggu sebelum memiliki anak?",
  "Apa yang kamu pelajari tentang pernikahan dari orang tua kamu?",
  "Apa yang kamu pelajari tentang kasih akung fisik dari orang tua kamu?",
  "Apa buku favoritmu?",
  "Apa lagu favoritmu?",
  "Apa film favorit pertama kamu, sebagai seorang anak?",
  "Apa yang ingin kamu lakukan saat pensiun?",
  "Pernahkah kamu membayangkan memiliki cucu?",
  "Apa karir lain yang menurut kamu akan kamu sukai?",
  "Apa fitur fisik favorit kamu sendiri?",
  "Siapa guru favorit kamu ketika kamu masih kecil?",
  "Apa kenangan favoritmu dengan ibumu?",
  "Apa kenangan favoritmu dengan ayahmu?",
  "Siapa orang penting sebelum aku yang memiliki dampak terbesar bagi kamu?",
  "Apa yang kamu pikirkan setelah pengalaman seksual pertama kamu?",
  "Lebih suka SMA atau kuliah?",
  "Ke mana kamu selalu ingin bepergian?",
  "Apakah kamu pernah mempertimbangkan jalur karir yang sama sekali berbeda?",
  "Apa kelas favorit kamu di sekolah menengah?",
  "Apa pesta terbaik yang pernah kamu datangi?",
  "Apa hal paling bahagia yang pernah kamu rasakan?",
  "Apa hal paling cemas yang pernah kamu rasakan?",
  "Apa hal paling marah yang pernah kamu rasakan?",
  "Apakah kamu percaya pada Tuhan?",
  "Apa pertanyaan yang belum pernah kamu tanyakan kepada aku?",
  "Apa ciri kepribadian favorit kamu sendiri?",
  "Manakah dari ciri kepribadian kamu yang ingin kamu ubah?",
  "Pernahkah kamu benar-benar terobsesi dengan suatu topik?",
  "Apakah kamu mengumpulkan barang-barang sebagai seorang anak?",
  "Manakah dari orang tua kamu yang kamu datangi ketika kamu ingin berbicara?",
  "Apa hal paling menakutkan yang pernah kamu rasakan, sebagai seorang anak?",
  "Apa pencapaian yang paling kamu banggakan?",
  "Di mana kamu ingin tinggal dalam 10 tahun?",
  "Manakah dari teman kamu yang akan kamu pilih jika kamu harus berada di pulau terpencil hanya dengan satu orang?",
  "Siapa di antara teman kamu yang paling mirip dengan kamu?",
  "Apa pendapat kamu tentang pasangan yang sudah menikah tetapi tinggal di kota yang berbeda?",
  "Apa pendapat kamu tentang pasangan yang memiliki bisnis bersama dan menghabiskan seluruh waktu mereka bersama?",
  "Mana yang paling kamu sukai: rumah musim panas, liburan selama setahun, atau perahu?",
  "Apa yang akan kamu lakukan dengan satu juta dolar?",
  "Apa yang akan kamu lakukan dengan tambahan .000 untuk dibelanjakan hanya untuk diri sendiri?",
  "Ketika kamu masih kecil, apakah kamu merasa cocok?",
  "Apa pelajaran favorit kamu di sekolah menengah?",
  "Apakah kamu mengalami pubertas sebelum atau sesudah orang lain, atau tepat waktu?",
  "Siapa naksir pertamamu?",
  "Siapa ciuman pertamamu?",
  "Siapa orang pertama yang naksir kamu?",
  "Menurut kamu, apakah kamu seorang introvert atau ekstrovert?",
  "Jika kamu bisa kembali ke masa lalu, umur berapa kamu akan kembali?",
  "Jika kamu bisa melihat ke masa depan, apa yang ingin kamu ketahui?",
  "Apa bakat terbesar kamu?",
  "Apa sifatmu yang paling unik?",
  "Apa yang membuat aku berbeda dari orang lain yang pernah bersama kamu?",
  "Apa hal terbaik tentang hubungan kita?",
  "Apakah kamu pernah membandingkan diri kamu dengan cowok/cewek lain?",
  "Manakah dari teman aku yang menurut kamu paling menyenangkan?",
  "Apakah kamu seorang yang optimis, pesimis, atau seorang realis ?",
  "Ketika kamu bangun di tengah malam, apa yang kamu pikirkan?",
  "Jika kamu harus mengubah satu hal tentang diri kamu, apa yang akan kamu pilih?",
  "Menurut kamu, apakah aku lebih optimis, pesimis, atau realistis?",
  "Sebagai seorang remaja, apakah kamu pernah memberontak terhadap orang tua kamu?",
  "Siapa orang terdekat kamu di keluarga besar kamu?",
  "Apakah kamu pernah menginginkan lebih atau lebih sedikit saudara kandung?",
  "Bagaimana saudara kandung membentuk diri kamu?",
  "Apa malam kencan favorit kamu yang pernah kita alami?",
  "Apa pikiran rahasia kamu ketika kamu melihat aku di penghujung hari?",
  "Apakah kamu pernah berharap aku bisa membaca pikiran kamu? Kapan?",
  "Hal-hal apa tentang aku yang membuat kamu tahu bahwa aku adalah orang yang tepat untuk kamu?",
  "Jika Anda mengasosiasikan cinta dengan gambar, apakah itu?",
  "Menurut Anda, apa 3 bahan utama untuk membuat suatu hubungan berhasil?",
  "Apa saja ciri-ciri yang harus dimiliki oleh pasangan ideal Anda?",
  "Namun, apa saja karakteristik yang seharusnya tidak dimiliki oleh pasangan ideal Anda?",
  "Bagaimana Anda biasanya berperilaku selama perkelahian pasangan? Lalu?",
  "Apa hal pertama yang Anda lihat dalam diri seseorang?",
  "Apa hal pertama yang Anda perhatikan dalam diri saya?",
  "Kohabitasi atau pernikahan?",
  "Bagaimana Anda mengelola pembagian pekerjaan rumah tangga?",
  "Bagaimana Anda ingin merayakan pernikahan Anda?",
  "Berapa banyak hubungan yang Anda miliki sebelum saya?",
  "Bagaimana dan mengapa hubungan Anda sebelumnya berakhir?",
  "Apa hubungan Anda dengan mantan Anda?",
  "Apa nilai terbaik saya?",
  "Apa hal yang paling mengganggumu tentang aku?",
  "Apa yang Anda ingin saya menjadi lebih baik dan mengapa? Dan kau?",
  "Kapan Anda menyadari bahwa Anda ingin bersamaku?",
  "Apa yang harus saya lakukan untuk membuat Anda benar-benar bahagia?",
  "Jika Anda mengalami masa sulit, apa yang akan Anda lakukan untuk membuat saya merasa baik?",
  "Apa yang harus kita upayakan agar hubungan kita lebih baik?",
  "Jika Anda harus mempersembahkan sebuah lagu untuk diri saya sendiri, lagu apakah itu?",
  "Kegilaan terbesar apa yang pernah Anda lakukan untuk cinta?",
  "Dalam latar belakang keluarga apa Anda dibesarkan?",
  "Hubungan apa yang Anda miliki dengan orang tua Anda?",
  "Apa kenangan terbaik yang berhubungan dengan masa kecil Anda?",
  "Dan yang paling jelek?",
  "Anak macam apa kamu?",
  "Bagaimana Anda mirip dengan ibu Anda dan bagaimana dengan ayah Anda?",
  "Bagaimana Anda ingin berbeda dari orang tua Anda?",
  "Apa yang akan Anda lakukan secara berbeda jika Anda berada di posisi orang tua?",
  "Apakah Anda lebih suka tinggal dekat atau jauh dari orang tua Anda?",
  "Apakah Anda akan tinggal dekat dengan keluarga saya?",
  "Jika orang tua Anda tidak menyukai saya, apa yang akan Anda lakukan?",
  "Jika keluarga saya tidak sepenuhnya yakin dengan hubungan kami, apa yang akan Anda lakukan agar diterima?",
  "Apa kekecewaan terbesar yang telah Anda berikan kepada orang tua Anda dan yang telah mereka berikan kepada Anda?",
  "Bagaimana Anda mengatasi saat-saat sulit di masa lalu?",
  "Apakah Anda merasa cemburu jika saya melihat orang lain?",
  "Apakah Anda merasa terganggu jika saya berbicara dengan teman Anda?",
  "Apa yang akan Anda lakukan jika orang lain memukul saya?",
  "Jika saya bertanya, apakah Anda akan mengizinkan saya melihat ponsel Anda?",
  "Apa pendapat Anda tentang persahabatan antara pria dan wanita?",
  "Apakah Anda merasa terganggu jika saya berbicara tentang mantan pasangan saya?",
  "Apa yang akan Anda rasakan jika saya tetap berhubungan baik dengan mantan saya?",
  "Jika Anda memiliki kesempatan untuk berhubungan seks dengan orang lain, tanpa ketahuan, apakah Anda akan melakukannya?",
  "Jika Anda selingkuh, maukah Anda memberi tahu saya?",
  "Jika saya mengkhianati Anda, apakah Anda ingin tahu?",
  "Bisakah Anda memaafkan pengkhianatan?",
  "Jika saya meninggalkan Anda untuk orang lain, bagaimana reaksi Anda?",
  "Apa yang akan Anda lakukan agar pengkhianatan diampuni?",
  "Bagaimana Anda akan berperilaku jika saya memberi tahu Anda bahwa Anda tertarik pada orang lain, tanpa melakukan apa pun?",
  "Seberapa penting seks bagi Anda dalam suatu hubungan?",
  "Bagaimana hal itu membuat Anda mendengar tentang seks secara terbuka dengan pasangan Anda?",
  "Biasanya, seberapa sering Anda harus berhubungan seks dalam seminggu?",
  "Berapa lama Anda bisa bertahan tanpa berhubungan seks?",
  "Apa fantasi terbesarmu?",
  "Apa posisi favoritmu?",
  "Di mana Anda suka disentuh?",
  "Apa tempat teraneh yang pernah Anda lakukan berhubungan seks?",
  "Seberapa penting foreplay bagi Anda?",
  "Apa ingatan paling memalukan yang Anda miliki terkait dengan seks?",
  "Dengan siapa dan bagaimana pertama kali Anda? Berapa usia Anda?",
  "Hal apa yang paling membuat Anda bersemangat?",
  "Apa yang membuat keinginan Anda tiba-tiba mereda?",
  "Apakah Anda ingin bereksperimen dengan mainan seks di tempat tidur?",
  "Apakah Anda ingin memiliki anak di masa depan?",
  "Jika ya, berapa banyak anak yang Anda inginkan?",
  "Nilai-nilai apa yang ingin Anda sampaikan kepada anak-anak Anda?",
  "Jika Anda mandul dan menginginkan anak, bagaimana Anda akan bersikap?",
  "Apa yang ingin Anda ajarkan kepada anak-anak Anda?",
  "Bagaimana Anda mengatur pendidikan anak-anak Anda?",
  "Apa hal yang paling membuat Anda takut tentang memiliki anak?",
  "Menurut Anda, pada usia berapa menjadi orang tua adalah hal yang benar?",
  "Apa kesalahan besar yang menurut Anda bisa dilakukan oleh orang tua?",
  "Apa yang Anda tidak ingin anak Anda beri tahu?",

  "Bagaimana Anda memandang diri Anda sendiri, bekerja sebagai pembicara, antara sekarang dan 10 tahun?",
  "Seberapa penting pekerjaan dalam hidup Anda?",
  "Apakah Anda pernah mengorbankan keluarga Anda untuk bekerja?",
  "Apakah Anda lebih suka mendapatkan pekerjaan yang selalu Anda impikan atau temukan cinta sejati?",
  "Jika Anda pindah karena alasan pekerjaan, apakah Anda akan menerima hubungan jarak jauh?",
  "Apakah Anda akan berhenti dari pekerjaan Anda, untuk pindah ke tempat lain dengan pasangan Anda?",
  "Bagaimana perasaan Anda jika pasangan Anda berpenghasilan lebih dari Anda?",

  "Bagaimana Anda biasanya menghabiskan akhir pekan?",
  "Apa yang Anda suka lakukan di waktu luang?",
  "Apakah Anda seorang olahragawan? Jika ya, olahraga apa yang Anda sukai?",
  "Anda suka bepergian?",
  "Jika kita bisa berangkat besok, kemana kamu ingin pergi?",
  "Apakah Anda lebih suka makan di rumah atau di restoran?",
  "Apa liburan ideal Anda?c Kota seni atau laut?",
  "Apa hobimu",
  "Kegiatan apa yang akan Anda lakukan sebagai pasangan dengan saya?",
  "Jika saya meminta Anda untuk melakukan sesuatu dengan saya / untuk saya yang sangat membuat Anda bosan, apakah Anda akan menerimanya?",
  "Apa yang benar-benar tidak bisa Anda serahkan?",
  "Apakah Anda siap melakukan hal-hal baru atau Anda lebih suka rutinitas?",
  "Apa yang akan Anda bawa ke pulau terpencil?",
  "Film malam dan pizza atau disko?",

  "Bagaimana Anda membayangkan hari-hari kita setelah kita pensiun?",
  "Jika saya sakit, bagaimana Anda akan merawat saya?",
  "Bagaimana Anda membayangkan seks setelah usia tertentu?",
  "Jika Anda punya pilihan, di mana Anda lebih suka menghabiskan masa tua?",
  "Menurut kamu, apa rahasia agar tidak cepat lelah setelah hidup bersama?",
  "a secret you kept from your parents 👀",
  "ain't no way",
  "any pets?",
  "are you a back seat driver?",
  "are you close with your parents?",
  "are you gonna get a tat",
  "are you judgemental",
  "are you looking to date someone rn",
  "are you straight?",
  "are you talking to anyone?",
  "Biggest red flags for a girl?",
  "biggest red flags in a guy?",
  "biggest regret?",
  "body count 😳?",
  "can we be besties",
  "craziest pickup line that worked?",
  "did you have an imaginary friend?",
  "did you watch game of thrones?",
  "do u have a dog?",
  "do u use pronouns",
  "do you even like school?",
  "do you have a middle name?",
  "do you have any cute friends for me lmao",
  "do you have any piercings?",
  "do you have trust issues?",
  "do you love ur life? x",
  "do you snore?",
  "do you speak another language?",
  "do you want kids evenutally?",
  "dogs or cats?",
  "dont leave me on opened",
  "dream job?",
  "ever gone skinny dipping?",
  "everything ok?",
  "favorite food?",
  "favorite movie?",
  "Favorite movie/ tv series rn",
  "favorite show rn?",
  "have any netflix recomendations??",
  "have any netlix recomendations?",
  "have u seen breaking bad",
  "have you done drugs 🍃",
  "Have you ever been fired from a job?",
  "have you ever cheated, you gotta be honest lol",
  "have you ever cried during a movie 🤷",
  "have you ever given a hickey?",
  "have you ever gotten in a fist fight?",
  "have you ever had any surgery",
  "have you ever thought about being bi",
  "have you ever watched harry potter?",
  "hottest sport? 🥵",
  "how are you feeling today :)",
  "How are you today ❤️‍🩹",
  "how big of nerd are you 1 to 10",
  "how many exes do you have?",
  "how many hours of sleep you get last night?",
  "how many kids do you want to have",
  "how many selfies do you take a day?",
  "how many stuffed animals you own?",
  "how old are you again?",
  "how old do u wanna be whe u get married?",
  "how tall are u",
  "how tall are you??",
  "how tall r u",
  "How's you day going ??!",
  "I have a crush on you",
  "I have covid, any show recomendations?",
  "I know what you did",
  "i love uuuuuu!!",
  "i miss you",
  "i really like you",
  "insta?",
  "introvert or extrovert?",
  "is it true???",
  "is ngl the best app tho :)",
  "kanye is the best 😤 change my mind",
  "name all your exes",
  "netflix and chill? 👀",
  "not gonna judge but why...",
  "one friend ur thankful for...",
  "one thing you can't survive without?",
  "opinion on birds?",
  "personality or looks?",
  "please give me pickup lines that always work",
  "should i be honest with you on here?",
  "shout me out",
  "single?",
  "spill some tea",
  "spill the tea on your first kiss.",
  "tell me a funny joke",
  "tell me a random fact",
  "the longest time you've ever gone without showering?",
  "the most embarrassing thing you've ever done?",
  "the weirdest place you've ever gone to the bathroom?",
  "the weirdest thing you've ever eaten?",
  "The weirdest trend you've done",
  "the worst advice you've ever given?",
  "the worst date you've ever been on?",
  "the worst food you ever eaten?",
  "the worst pick up line you've ever heard?",
  "the worst trouble you go into as a kid?",
  "u busy this weekend?",
  "uh what did you eat for breakfast?",
  "we should talk more",
  "what are ur plans this weekend?",
  "what are you wearing?",
  "what color is your room?",
  "what did you dream about last night?",
  "what have you gotten detention for?",
  "What is your shoe size?",
  "what music do you listen to",
  "what phone do you have?",
  "what time did you fall asleep last night?",
  "what time do you usually go to bed?",
  "what was the best day so far this year?",
  "what was ur worst day ever",
  "what was your favorite show when you were a kid?",
  "What's ur fav brand?? <3",
  "whats in ur spotify top songs",
  "whats the last thing you ate?",
  "whats the stupidest thing you thought as a kid?",
  "whats ur fav book",
  "whats ur fav drink",
  "whats ur fav food",
  "whats ur fav movie",
  "whats ur fav song",
  "whats ur fav tv show",
  "whats ur favorite food?",
  "whats ur oritenation",
  "whats your biggest insecurity 🤔",
  "whats your dream house",
  "whats your fav sport?",
  "whats your number one song on spotify",
  "whats your sign",
  "when was the last time you cried?",
  "when was the last time you lied?",
  "when was the last time you wet the bed?",
  "when was your first kiss?",
  "where are you from...?",
  "where are your parents from?",
  "who are your best girl friends",
  "who do you have pinned on imessage",
  "who do you miss the most",
  "who do you text the most?",
  "who was the last dude you texted?",
  "who was the last girl you texted?",
  "who was your crush in middle school lmao",
  "who was your first kiss?",
  "who you tryna get with 👀",
  "who you tryna vote for in 2024 👀",
  "whos the last person you texted?",
  "whos ur best friend",
  "whos ur crush?",
  "whos ur worst enemy 😈",
  "whos your last ig search?",
  "whos your last snap from?",
  "why doesnt my crush like me back 😭",
  "worst movie youve ever watched?",
  "would you ever be fwb",
  "would you ever get with me? ~ N",
  "would you leave your SO for a celeb",
  "would you say yes if i asked you out - A",
  "wyd",
  "wyd tomorrow",
  "yo stop leaving me on read",
  "you a homie",
  "you ever think about having the ability to teleport?",
  "you got a sneaky link?",
  "you have good style",
  "you lit",
  "you should get a tattoo",
  "you should post more selfies 💕",
  "you wild for what you did",
  "you're best friend",
  "Your biggest fear?",
  "your biggest insecurity?",
  "your celeb crush?",
  "your favorite hobby?",
  "your favorite part of your body?",
  "your last song on your spotify?",
  "your really attractive",
  "your worst habit?",
  "your worst personality characteristic?",
  "youre cute",
];
